log:
  level: WARN
  filePath: /logs/traefik.log
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
  file:
    filename: /etc/traefik/dynamic.yml

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections: # Redirect everything to https
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  default:
    acme:
      email: example@mail.invalid
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
